author: Abhishek Raj
email: raj.abhishek.01.1@gmail.com

title: My Wiki
description: Basic Site to store what I discover
 
github_username: abhishek-raj
linkedin_username: abhishek-raj-b8a493123

# build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
