author:
 name: Abhishek Raj
 email: raj.abhishek.01.1@gmail.com

title: My Wiki
description: Basic Site to store what I discover
 
minima:
 social_links:
  github: abhishek-raj
 skin: dark

theme: minima
